# Generated by Django 4.2.16 on 2024-09-13 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subtitles',
            new_name='Subtitle',
        ),
    ]
