# Generated by Django 4.2.16 on 2024-09-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_rename_subtitles_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitle',
            name='timestamp',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
